prefix: ""
appeal: ""
vanity: ""

logging:
    modLogs: ""
    snippetLogs: ""
guilds:
    main: ""
    staff: ""
suggestions:
    main: ""
    staff: ""
    discussion:
        main: ""
        staff: ""
suggestionOffset:
    main: 0
    staff: 0
reactionRoles:
    <channel ID>:
        <message ID>:
            <guild emoji ID or unicode emoji>: "<role ID>"

images:
    bindPort: 8080
    bindAddress: "127.0.0.1"

emojis:
    upvote: ğŸ‘
    downvote: ğŸ‘
    left: ğŸ¡
    right: ğŸ¡’
    text:
        online: ğŸŸ¢
        idle: ğŸŒ™
        dnd: ğŸ”´
        offline: âš«
colors:
    success: "#1EAD2F"
    error: "#ED5439"
    info: "#28338C"
    suggestions:
        approved: "#4B53EB"
        denied: "#EB4364"
        duplicate: "#E5B823"
        forwarded: "#D25424"
        in-progress: "#E5B823"
        information: "#62D18A"
        invalid: "#EB4364"

assets:
    suggestions:
        approved: https://i.imgur.com/ttZm92O.png
        denied: https://i.imgur.com/3RjU2cu.png
        duplicate: https://i.imgur.com/21C2CPw.png
        forwarded: https://i.imgur.com/21Xcn53.png
        in-progress: https://i.imgur.com/hJt4Cjs.png
        information: https://i.imgur.com/JToVhw7.png
        invalid: https://i.imgur.com/1srPUeR.png
    cases:
        warn: https://i.imgur.com/HvFuorQ.png
        mute: https://i.imgur.com/32AebCX.png
        kick: https://i.imgur.com/KJuo0kL.png
        ban: https://i.imgur.com/6WpHhM5.png
        unmute: https://i.imgur.com/ZC0qrC9.png
        unban: https://i.imgur.com/PfrLhuO.png

rules: []
buildTeamInvites: {}

token: ""
modpackAuth: ""
database:
    type: ""
    host: ""
    name: ""
    user: ""
    pass: ""
